### ISSUE TITLE
Got below issue

### ISSUE THREAD

**Issue by InCodingNowLiu** [Binaryify/amrToMp3#1]
error:ffmpeg version 3.4-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
0|server   |   built with gcc 6.4.0 (Debian 6.4.0-7) 20170920
0|server   |   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
0|server   |   libavutil      55. 78.100 / 55. 78.100
0|server   |   libavcodec     57.107.100 / 57.107.100
0|server   |   libavformat    57. 83.100 / 57. 83.100
0|server   |   libavdevice    57. 10.100 / 57. 10.100
0|server   |   libavfilter     6.107.100 /  6.107.100
0|server   |   libswscale      4.  8.100 /  4.  8.100
0|server   |   libswresample   2.  9.100 /  2.  9.100
0|server   |   libpostproc    54.  7.100 / 54.  7.100
0|server   | public/wxVoice/Cb6UNFNr8GY7-7o-eCVFOUqB5UEt0UchtnZJrp0C2hKK9e45BnAisFbur8mXUHkS.amr: Invalid data found when processing input

**Comment by Binaryify** [comment]
make sure you create the output folder first
